version: "3.8"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=admin@4dm1N

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=admin@4dm1N

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7071:7071
    volumes:
      - ./:/app
    depends_on:
      - azurite
      - mssql
      - mongo
